name: cruzhacks-2023-website-development

env:
  REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN_DEV }}
  REACT_APP_AUTH0_CLIENTID: ${{ secrets.REACT_APP_AUTH0_CLIENTID_DEV }}
  REACT_APP_AUTH0_AUDIENCE: ${{ secrets.REACT_APP_AUTH0_AUDIENCE_DEV }}
  REACT_APP_RECAPTCHA_SITE_KEY: ${{ secrets.REACT_APP_RECAPTCHA_SITE_KEY }}
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY_DEV }}
  REACT_APP_ENDPOINT_URL: ${{ secrets.REACT_APP_ENDPOINT_URL_DEV }}
  REACT_APP_CORS_ORIGIN: ${{ secrets.REACT_APP_CORS_ORIGIN_DEV }}
  REACT_APP_FIREBASE_VAPID_KEY: ${{ secrets.REACT_APP_FIREBASE_VAPID_KEY_DEV }}
  REACT_APP_FIREBASE_CONFIG: ${{ secrets.REACT_APP_FIREBASE_CONFIG_DEV }}

on:
  push:
    branches: [development]
  pull_request:
    branches: [development, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create Production Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create Test Build
        run: yarn build
      - name: Running JS tests
        run: yarn test:ci
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint Typescript
        run: yarn lint:ts
      - name: Lint CSS
        run: yarn lint:css

  auto-deploy-to-test:
    runs-on: ubuntu-latest
    needs: [build, lint, tests]
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          REACT_APP_MODE: ${{ secrets.MODE_DEV }} 
      - name: Deploy to Firebase -- Test
        run: yarn deploy:dev --token $token
        env:
          token: ${{ secrets.FIREBASE_TOKEN }}